Repository wolfSSL/wolfssl, pull requests merged in 2023-06, with the labels that each got.

#6476 Send blank certificate message in DTLS when no client cert is loaded.
  src/internal.c
Labels: For This Release

#6483 cppcheck: fixes from scan
  IDE/MCUEXPRESSO/wolfcrypt_test.c
  IDE/Renesas/e2studio/RA6M4/test/src/test_main.c
  IDE/Renesas/e2studio/RA6M4/test/src/wolfssl_sce_unit_test.c
  IDE/Renesas/e2studio/RX72N/EnvisionKit/wolfssl_demo/wolfssl_demo.c
  IDE/Renesas/e2studio/RX72N/EnvisionKit/wolfssl_demo/wolfssl_tsip_unit_test.c
  IDE/iotsafe/devices.c
  src/bio.c
  src/conf.c
  src/internal.c
  src/ssl.c
  src/ssl_asn1.c
  src/x509.c
  tests/api.c
  wolfcrypt/src/aes.c
  wolfcrypt/src/asn.c
  wolfcrypt/src/des3.c
  wolfcrypt/src/fe_448.c
  wolfcrypt/src/fe_operations.c
  wolfcrypt/src/ge_low_mem.c
  wolfcrypt/src/hmac.c
  wolfcrypt/src/kdf.c
  wolfcrypt/src/port/kcapi/kcapi_hash.c
  wolfcrypt/src/port/kcapi/kcapi_rsa.c
  wolfcrypt/src/port/st/stm32.c
  wolfcrypt/src/random.c
  wolfcrypt/src/sakke.c
  wolfcrypt/src/wc_port.c
Labels: For This Release

#6482 Regression testing fixes
  src/ssl.c
  tests/api.c
  wolfcrypt/test/test.c
Labels: For This Release

#6471 Test api.c: change more tests to use Expect instead of Assert
  src/bio.c
  src/crl.c
  src/ssl.c
  src/ssl_asn1.c
  src/x509.c
  src/x509_str.c
  tests/api.c
Labels: For This Release

#6478 Kyber: allow compilation with limited sizes with liboqs
  configure.ac
  wolfssl/wolfcrypt/asn_public.h
  wolfssl/wolfcrypt/settings.h
Labels: For This Release

#6484 coverity scan fixes
  src/bio.c
  src/pk.c
  src/x509.c
  wolfcrypt/src/asn.c
Labels: For This Release

#6477 add sanity check on hash size with STM32 port
  wolfcrypt/src/port/st/stm32.c
Labels: For This Release

#6487 sanity check on socket return value for timeout with DTLS13
  src/internal.c
Labels: For This Release

#6488 20230608-linuxkm-__is_constexpr
  linuxkm/linuxkm_wc_port.h
Labels: For This Release

#6512 Math, Encrypted Memory: mod exp fix
  wolfcrypt/src/sp_int.c
  wolfcrypt/src/tfm.c
Labels: For This Release

#6508 sanity check on send fatal alert return
  src/dtls13.c
  src/internal.c
  src/tls13.c
  tests/api.c
  wolfssl/internal.h
Labels: For This Release

#6518 Release 5.6.3
  ChangeLog.md
  README
  README.md
Labels: For This Release

#6503 TFM: fix big endian reading a zero length buffer
  wolfcrypt/src/tfm.c
Labels: Not For This Release

#6505 ECC, ALT_ECC_SIZE, CryptoCB: ensure err is 0 in _ecc_make_key_ex
  wolfcrypt/src/ecc.c
Labels: Not For This Release

#6504 test.c, scrypt: bench embedded reduce heap usage
  wolfcrypt/test/test.c
Labels: Not For This Release

#6549 Revert #6536 types.h one line HAVE_PTHREAD
  wolfssl/wolfcrypt/types.h
Labels: bug
