Repository wolfSSL/wolfssl, pull requests merged in 2024-02, with the labels that each got.

#7220 Introduce MICRO_SESSION_CACHE, update comments
  src/ssl.c
Labels: enhancement

#7223 Add wolfSSL debug messages
  src/internal.c
  src/ssl.c
  src/ssl_certman.c
  src/tls.c
  src/tls13.c
  wolfcrypt/src/aes.c
  wolfcrypt/src/ecc.c
  wolfcrypt/src/md5.c
  wolfcrypt/src/random.c
  wolfcrypt/src/rsa.c
Labels: enhancement

#7177 Improved Arduino Support: ESP32, Due
  .gitignore
  IDE/ARDUINO/Arduino_README_prepend.md
  IDE/ARDUINO/README.md
  IDE/ARDUINO/include.am
  IDE/ARDUINO/keywords.txt
  IDE/ARDUINO/library.properties.template
  IDE/ARDUINO/sketches/README.md
  IDE/ARDUINO/sketches/wolfssl_client/README.md
  IDE/ARDUINO/sketches/wolfssl_server/README.md
  IDE/ARDUINO/wolfssl-arduino.sh
  examples/configs/include.am
  examples/configs/user_settings_arduino.h
  wolfcrypt/src/random.c
  wolfssl/ssl.h
  wolfssl/test.h
  wolfssl/wolfcrypt/settings.h
  wolfssl/wolfcrypt/tfm.h
  wolfssl/wolfcrypt/wc_port.h
  wolfssl/wolfio.h
Labels: enhancement, help wanted, New Chipset

#7229 Windows doesn't like code before variables
  wolfcrypt/src/tfm.c
Labels: For This Release
