Repository wolfSSL/wolfssl, pull requests merged in 2024-03, with the labels that each got.

#7262 Introduce SHA256/SHA512 interleave testing, HAVE_DSA; revised ERROR_OUT
  src/pk.c
  wolfcrypt/src/port/Espressif/esp32_sha.c
  wolfcrypt/test/test.c
  wolfssl/wolfcrypt/settings.h
Labels: bug, enhancement

#7240 Update TLS client example for Espressif ESP8266
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/Makefile
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/README.md
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/VisualGDB/wolfssl_client_IDF_v5_ESP32.sln
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/components/wolfssl/CMakeLists.txt
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/components/wolfssl/component.mk
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/components/wolfssl/include/user_settings.h
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/main/client-tls.c
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/main/component.mk
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/main/include/client-tls.h
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/main/include/main.h
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/main/include/time_helper.h
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/main/include/wifi_connect.h
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/main/main.c
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/main/time_helper.c
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/main/wifi_connect.c
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/sdkconfig.defaults
  IDE/Espressif/ESP-IDF/examples/wolfssl_client/wolfssl_client_ESP8266.vgdbproj
  IDE/Espressif/README.md
  IDE/Espressif/include.am
  wolfcrypt/benchmark/benchmark.c
  wolfcrypt/src/port/Espressif/esp32_mp.c
  wolfcrypt/src/port/Espressif/esp32_sha.c
  wolfcrypt/src/port/Espressif/esp32_util.c
  wolfcrypt/src/sha256.c
  wolfcrypt/src/sha512.c
  wolfssl/wolfcrypt/port/Espressif/esp32-crypt.h
Labels: enhancement

#7067 Introduce WOLFSSL_ESPIDF_EXIT_MESSAGE macro
  IDE/Espressif/ESP-IDF/examples/wolfssl_benchmark/main/main.c
  wolfssl/wolfcrypt/port/Espressif/esp32-crypt.h
Labels: Feature Request

#7321 fix for warning of no stdint.h include with uintptr_t
  src/ssl.c
  src/tls.c
Labels: For This Release

#7329 Ignore build file warnings for Arduino; Update examples
  IDE/ARDUINO/README.md
  IDE/ARDUINO/include.am
  IDE/ARDUINO/sketches/wolfssl_client/wolfssl_client.ino
  IDE/ARDUINO/sketches/wolfssl_server/wolfssl_server.ino
  IDE/ARDUINO/sketches/wolfssl_version/README.md
  IDE/ARDUINO/sketches/wolfssl_version/wolfssl_version.ino
  IDE/ARDUINO/wolfssl-arduino.sh
  examples/configs/user_settings_arduino.h
  wolfssl/wolfcrypt/settings.h
Labels: For This Release

#7306 ASN.1 template: validate UTF8STRING and OBJECT IDENTIFER data
  wolfcrypt/src/asn.c
Labels: For This Release

#7318 Kyber: Implementation in wolfSSL
  configure.ac
  wolfcrypt/src/wc_kyber.c
  wolfcrypt/src/wc_kyber_asm.S
  wolfcrypt/src/wc_kyber_poly.c
  wolfssl/wolfcrypt/wc_kyber.h
Labels: For This Release

#7336 20240314 -- fix -Wconversions in asn.c
  wolfcrypt/src/asn.c
Labels: For This Release

#7339 Regression testing fixes
  tests/api.c
  wolfcrypt/benchmark/benchmark.c
  wolfcrypt/src/cmac.c
  wolfcrypt/test/test.c
  wolfssl/test.h
Labels: For This Release

#7332 ASN.1 parsing: check for badly encode negative INTEGER
  wolfcrypt/src/asn.c
Labels: For This Release

#7341 Fix for PSK callback with OPENSSL_EXTRA to correctly handle the 0 length
  src/tls.c
Labels: For This Release

#7342 revert null check in wc_Sha256Update
  wolfcrypt/src/sha256.c
Labels: For This Release

#7346 Regression test fixes
  wolfcrypt/src/pkcs7.c
  wolfcrypt/test/test.c
Labels: For This Release

#7331 ASN.1 template: store issuer common name
  wolfcrypt/src/asn.c
Labels: For This Release

#7348 Coverity fixes
  src/tls13.c
Labels: For This Release

#7343 20240315-pq-experimental
  configure.ac
  tests/api.c
  wolfcrypt/src/wc_kyber_poly.c
  wolfssl/wolfcrypt/settings.h
  wolfssl/wolfcrypt/wc_kyber.h
Labels: For This Release

#7350 scan-build fixes for pkcs7
  wolfcrypt/src/pkcs7.c
Labels: For This Release

#7351 20240318-linuxkm-lkcapi-register-yes
  configure.ac
Labels: For This Release

#7353 OCSP Extension Encoding Fix
  wolfcrypt/src/asn.c
Labels: bug, For This Release

#7337 wolfcrypt tests: improve file system gating for USE_CERT_BUFFERS
  wolfcrypt/test/test.c
Labels: enhancement
